version: '3.6'

services:
  dynamodb:
    image: 'amazon/dynamodb-local:1.17.0'
    container_name: dynamodb
    command:
      - '-jar'
      - 'DynamoDBLocal.jar'
      - '-inMemory'
    ports:
      - "8000:8000"
    networks:
      - local

#  db-init:
#    image: 'amazon/aws-cli:2.4.6'
#    container_name: db-init
#    environment:
#      AWS_ACCESS_KEY_ID: 'defaultkey'
#      AWS_SECRET_ACCESS_KEY: 'defaultsecret'
##    command: |
##      dynamodb describe-limits --endpoint-url http://dynamodb:8000 --region us-east-1
#    command:
#      dynamodb create-table --table-name notes --attribute-definitions AttributeName=owner,AttributeType=S AttributeName=title,AttributeType=S --key-schema AttributeName=owner,KeyType=HASH AttributeName=title,KeyType=RANGE --billing-mode PAY_PER_REQUEST --endpoint-url http://dynamodb:8000 --region us-east-1
#    depends_on:
#      - dynamodb
#    networks:
#      - local

networks:
  local:
    name: aws-sam-local